### ISSUE TITLE
maximize the player screen on iPhone

### ISSUE THREAD

**Issue by t-cool** [geg-nara/youtuben#1]
I'd like to keep the screen from maximizing when youtube player plays on iPhone.

**Comment by tanykazy** [comment]
関係ありそうなリンクを貼っておきます。

https://developers.google.com/youtube/player_parameters#playsinline
https://developer.mozilla.org/ja/docs/Web/HTML/Element/video
https://qiita.com/tomoyukilabs/items/cb9dd1d3e7eb0cc7f58a#%E3%82%A4%E3%83%B3%E3%83%A9%E3%82%A4%E3%83%B3%E5%86%8D%E7%94%9F%E3%81%AE%E5%AF%BE%E5%BF%9C-safari
https://developers.google.com/youtube/iframe_api_reference#getVideoEmbedCode

**Comment by t-cool** [comment]
ありがとうございます！
